// Code generated by go-swagger; DO NOT EDIT.

package clientmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EventTriggerDefinition E2SM Octet string
// swagger:model EventTriggerDefinition
type EventTriggerDefinition struct {

	// octet string
	OctetString string `json:"OctetString,omitempty"`
}

// Validate validates this event trigger definition
func (m *EventTriggerDefinition) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EventTriggerDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventTriggerDefinition) UnmarshalBinary(b []byte) error {
	var res EventTriggerDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
