// Code generated by go-swagger; DO NOT EDIT.

package clientmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// EventTriggerDefinition E2SM byte array
//
// swagger:model EventTriggerDefinition
type EventTriggerDefinition []int64

// Validate validates this event trigger definition
func (m EventTriggerDefinition) Validate(formats strfmt.Registry) error {
	return nil
}
