// Code generated by go-swagger; DO NOT EDIT.

package clientmodel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ReportActionDefinition report action definition
// swagger:model ReportActionDefinition
type ReportActionDefinition struct {

	// action definition format1
	ActionDefinitionFormat1 *Format1ActionDefinition `json:"ActionDefinitionFormat1,omitempty"`
}

// Validate validates this report action definition
func (m *ReportActionDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActionDefinitionFormat1(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ReportActionDefinition) validateActionDefinitionFormat1(formats strfmt.Registry) error {

	if swag.IsZero(m.ActionDefinitionFormat1) { // not required
		return nil
	}

	if m.ActionDefinitionFormat1 != nil {
		if err := m.ActionDefinitionFormat1.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ActionDefinitionFormat1")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ReportActionDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReportActionDefinition) UnmarshalBinary(b []byte) error {
	var res ReportActionDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
