// Code generated by go-swagger; DO NOT EDIT.

// Package restapi RIC subscription
//
//  This is the initial REST API for RIC subscription
//  Schemes:
//    http
//  Host: hostname
//  BasePath: /ric/v1
//  Version: 0.0.2
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//    - application/xml
//
// swagger:meta
package restapi
