// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "gerrit.o-ran-sc.org/r/ric-plt/xapp-frame/pkg/models"
)

// NewSubscribeReportParams creates a new SubscribeReportParams object
// no default values defined in spec.
func NewSubscribeReportParams() SubscribeReportParams {

	return SubscribeReportParams{}
}

// SubscribeReportParams contains all the bound params for the subscribe report operation
// typically these are obtained from a http.Request
//
// swagger:parameters subscribeReport
type SubscribeReportParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Subscription report parameters
	  In: body
	*/
	ReportParams *models.ReportParams
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSubscribeReportParams() beforehand.
func (o *SubscribeReportParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ReportParams
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("reportParams", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ReportParams = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
