// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ActionDefinition E2SM Octet string. ActionDefinition is an OPTIONAL IE
// swagger:model ActionDefinition
type ActionDefinition struct {

	// octet string
	OctetString string `json:"OctetString,omitempty"`
}

// Validate validates this action definition
func (m *ActionDefinition) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionDefinition) UnmarshalBinary(b []byte) error {
	var res ActionDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
