// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ActionParameters action parameters
// swagger:model ActionParameters
type ActionParameters struct {

	// action parameter ID
	// Required: true
	ActionParameterID *int64 `json:"ActionParameterID"`

	// action parameter value
	// Required: true
	ActionParameterValue *bool `json:"ActionParameterValue"`
}

// Validate validates this action parameters
func (m *ActionParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActionParameterID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateActionParameterValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActionParameters) validateActionParameterID(formats strfmt.Registry) error {

	if err := validate.Required("ActionParameterID", "body", m.ActionParameterID); err != nil {
		return err
	}

	return nil
}

func (m *ActionParameters) validateActionParameterValue(formats strfmt.Registry) error {

	if err := validate.Required("ActionParameterValue", "body", m.ActionParameterValue); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ActionParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionParameters) UnmarshalBinary(b []byte) error {
	var res ActionParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
