// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// ActionDefinition E2SM byte array. ActionDefinition is an OPTIONAL IE
//
// swagger:model ActionDefinition
type ActionDefinition []int64

// Validate validates this action definition
func (m ActionDefinition) Validate(formats strfmt.Registry) error {
	return nil
}
