// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PolicyParams policy params
// swagger:model PolicyParams
type PolicyParams struct {

	// requestor Id
	RequestorID int64 `json:"RequestorId,omitempty"`

	// t b d
	TBD string `json:"TBD,omitempty"`
}

// Validate validates this policy params
func (m *PolicyParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyParams) UnmarshalBinary(b []byte) error {
	var res PolicyParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
