// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubscriptionResponse subscription response
//
// swagger:model SubscriptionResponse
type SubscriptionResponse struct {

	// subscription Id
	// Required: true
	SubscriptionID *string `json:"SubscriptionId"`

	// subscription instances
	// Required: true
	SubscriptionInstances []*SubscriptionInstance `json:"SubscriptionInstances"`
}

// Validate validates this subscription response
func (m *SubscriptionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubscriptionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSubscriptionInstances(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubscriptionResponse) validateSubscriptionID(formats strfmt.Registry) error {

	if err := validate.Required("SubscriptionId", "body", m.SubscriptionID); err != nil {
		return err
	}

	return nil
}

func (m *SubscriptionResponse) validateSubscriptionInstances(formats strfmt.Registry) error {

	if err := validate.Required("SubscriptionInstances", "body", m.SubscriptionInstances); err != nil {
		return err
	}

	for i := 0; i < len(m.SubscriptionInstances); i++ {
		if swag.IsZero(m.SubscriptionInstances[i]) { // not required
			continue
		}

		if m.SubscriptionInstances[i] != nil {
			if err := m.SubscriptionInstances[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("SubscriptionInstances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionResponse) UnmarshalBinary(b []byte) error {
	var res SubscriptionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
