// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gerrit.o-ran-sc.org/r/ric-plt/xapp-frame/pkg/clientmodel"
)

// GetXappConfigListReader is a Reader for the GetXappConfigList structure.
type GetXappConfigListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetXappConfigListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetXappConfigListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetXappConfigListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetXappConfigListOK creates a GetXappConfigListOK with default headers values
func NewGetXappConfigListOK() *GetXappConfigListOK {
	return &GetXappConfigListOK{}
}

/*GetXappConfigListOK handles this case with default header values.

successful query of xApp config
*/
type GetXappConfigListOK struct {
	Payload clientmodel.XappConfigList
}

func (o *GetXappConfigListOK) Error() string {
	return fmt.Sprintf("[GET /config][%d] getXappConfigListOK  %+v", 200, o.Payload)
}

func (o *GetXappConfigListOK) GetPayload() clientmodel.XappConfigList {
	return o.Payload
}

func (o *GetXappConfigListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetXappConfigListInternalServerError creates a GetXappConfigListInternalServerError with default headers values
func NewGetXappConfigListInternalServerError() *GetXappConfigListInternalServerError {
	return &GetXappConfigListInternalServerError{}
}

/*GetXappConfigListInternalServerError handles this case with default header values.

Internal error
*/
type GetXappConfigListInternalServerError struct {
}

func (o *GetXappConfigListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /config][%d] getXappConfigListInternalServerError ", 500)
}

func (o *GetXappConfigListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
