// Code generated by go-swagger; DO NOT EDIT.

package report

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new report API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for report API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
SubscribeReport subscribes a list of x2 a p event triggers to receive r e p o r t messages sent by r a n
*/
func (a *Client) SubscribeReport(params *SubscribeReportParams) (*SubscribeReportCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSubscribeReportParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "subscribeReport",
		Method:             "POST",
		PathPattern:        "/subscriptions/report",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SubscribeReportReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*SubscribeReportCreated), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
