// Code generated by go-swagger; DO NOT EDIT.

package common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnsubscribeParams creates a new UnsubscribeParams object
// no default values defined in spec.
func NewUnsubscribeParams() UnsubscribeParams {

	return UnsubscribeParams{}
}

// UnsubscribeParams contains all the bound params for the unsubscribe operation
// typically these are obtained from a http.Request
//
// swagger:parameters Unsubscribe
type UnsubscribeParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The subscriptionId to be unsubscribed
	  Required: true
	  In: path
	*/
	SubscriptionID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUnsubscribeParams() beforehand.
func (o *UnsubscribeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSubscriptionID, rhkSubscriptionID, _ := route.Params.GetOK("subscriptionId")
	if err := o.bindSubscriptionID(rSubscriptionID, rhkSubscriptionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSubscriptionID binds and validates parameter SubscriptionID from path.
func (o *UnsubscribeParams) bindSubscriptionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("subscriptionId", "path", "int64", raw)
	}
	o.SubscriptionID = value

	return nil
}
