// Code generated by go-swagger; DO NOT EDIT.

package common

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UnsubscribeNoContentCode is the HTTP code returned for type UnsubscribeNoContent
const UnsubscribeNoContentCode int = 204

/*UnsubscribeNoContent Operation done successfully

swagger:response unsubscribeNoContent
*/
type UnsubscribeNoContent struct {
}

// NewUnsubscribeNoContent creates UnsubscribeNoContent with default headers values
func NewUnsubscribeNoContent() *UnsubscribeNoContent {

	return &UnsubscribeNoContent{}
}

// WriteResponse to the client
func (o *UnsubscribeNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// UnsubscribeBadRequestCode is the HTTP code returned for type UnsubscribeBadRequest
const UnsubscribeBadRequestCode int = 400

/*UnsubscribeBadRequest Invalid subscriptionId supplied

swagger:response unsubscribeBadRequest
*/
type UnsubscribeBadRequest struct {
}

// NewUnsubscribeBadRequest creates UnsubscribeBadRequest with default headers values
func NewUnsubscribeBadRequest() *UnsubscribeBadRequest {

	return &UnsubscribeBadRequest{}
}

// WriteResponse to the client
func (o *UnsubscribeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UnsubscribeInternalServerErrorCode is the HTTP code returned for type UnsubscribeInternalServerError
const UnsubscribeInternalServerErrorCode int = 500

/*UnsubscribeInternalServerError Internal error

swagger:response unsubscribeInternalServerError
*/
type UnsubscribeInternalServerError struct {
}

// NewUnsubscribeInternalServerError creates UnsubscribeInternalServerError with default headers values
func NewUnsubscribeInternalServerError() *UnsubscribeInternalServerError {

	return &UnsubscribeInternalServerError{}
}

// WriteResponse to the client
func (o *UnsubscribeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
