// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"gerrit.o-ran-sc.org/r/ric-plt/xapp-frame/pkg/models"
)

// GetXappConfigListOKCode is the HTTP code returned for type GetXappConfigListOK
const GetXappConfigListOKCode int = 200

/*GetXappConfigListOK successful query of xApp config

swagger:response getXappConfigListOK
*/
type GetXappConfigListOK struct {

	/*
	  In: Body
	*/
	Payload models.XappConfigList `json:"body,omitempty"`
}

// NewGetXappConfigListOK creates GetXappConfigListOK with default headers values
func NewGetXappConfigListOK() *GetXappConfigListOK {

	return &GetXappConfigListOK{}
}

// WithPayload adds the payload to the get xapp config list o k response
func (o *GetXappConfigListOK) WithPayload(payload models.XappConfigList) *GetXappConfigListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get xapp config list o k response
func (o *GetXappConfigListOK) SetPayload(payload models.XappConfigList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetXappConfigListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.XappConfigList{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetXappConfigListInternalServerErrorCode is the HTTP code returned for type GetXappConfigListInternalServerError
const GetXappConfigListInternalServerErrorCode int = 500

/*GetXappConfigListInternalServerError Internal error

swagger:response getXappConfigListInternalServerError
*/
type GetXappConfigListInternalServerError struct {
}

// NewGetXappConfigListInternalServerError creates GetXappConfigListInternalServerError with default headers values
func NewGetXappConfigListInternalServerError() *GetXappConfigListInternalServerError {

	return &GetXappConfigListInternalServerError{}
}

// WriteResponse to the client
func (o *GetXappConfigListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
